backend:
  name: git-gateway
  branch: main # Vérifie que ta branche GitHub s'appelle bien main

media_folder: "public/images" # Où seront stockées les photos de tes articles
public_folder: "/images"

collections:
  - name: "blog"
    label: "Articles de Blog"
    folder: "src/content/blog"
    create: true # Autorise la création de nouveaux fichiers
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date de publication", name: "pubDate", widget: "datetime" }
      - { label: "Image de couverture", name: "heroImage", widget: "image" }
      - { 
          label: "Catégorie", 
          name: "category", 
          widget: "select", 
          options: ["Actu", "Analyse", "Draft", "Histoire", "Breaking News"] 
        }
      - { label: "Mots-clés SEO", name: "tags", widget: "list", default: ["Miami Dolphins", "NFL France"] }
      - { label: "Cacher l'article ?", name: "draft", widget: "boolean", default: false }
      - { label: "Corps de l'article", name: "body", widget: "markdown" }