backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Articles de Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Date de publication", name: "pubDate", widget: "datetime" }
      - { label: "Image de couverture", name: "heroImage", widget: "image" }
      - { 
          label: "Catégorie", 
          name: "category", 
          widget: "select", 
          options: ["Actu", "Analyse", "Histoire", "Breaking News"] 
        }
      - { label: "Mots-clés SEO", name: "tags", widget: "list", default: ["Miami Dolphins", "NFL France"] }
      - { label: "Cacher l'article ?", name: "draft", widget: "boolean", default: false }
      - { label: "Corps de l'article", name: "body", widget: "markdown" }
      - {
          label: "Auteur",
          name: "author",
          widget: "select",
          options: ["Cyril", "Lucas Roc", "FCFRMD", "Redaction Phin Side"],
          default: "Rédaction Phin Side"
      }